[package]
name = "raytracer_codegen"
version = "0.1.0"
authors = ["aik2mlj <aik2mlj@sjtu.edu.cn>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
rand = { version = "0.7", features = ["small_rng"] }
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
